import json
import shutil
import subprocess
from pathlib import Path
from PIL import Image, ImageChops

class PDFVisualHelper:
    def __init__(self, project, scenario_dir: Path, update_baselines: bool = False):
        self.project = project
        self.scenario_dir = scenario_dir
        self.baseline_dir = scenario_dir / "baselines"
        self.update_baselines = update_baselines
        self.baseline_dir.mkdir(exist_ok=True)
        self.steps = []

    def verify_publication(self, publication_path: Path, seed: str, variant: str):
        from mathpub.publish import build
        
        # Build publication using the core library function
        result = build(
            self.project,
            self.project.root / publication_path,
            root_seed=seed,
            variant=variant,
            replace=True
        )
        
        edition_dir = self.project.root / result["edition"]
        manifest_path = edition_dir / "manifest.json"
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        
        for output in manifest["outputs"]:
            projection = output["projection"]
            pdf_path = edition_dir / output["path"]
            
            # Convert PDF pages to 150 DPI PNGs using pdftoppm
            tmp_prefix = edition_dir / f"temp-{projection}"
            subprocess.run([
                "pdftoppm", "-png", "-r", "150",
                str(pdf_path), str(tmp_prefix)
            ], check=True)
            
            # Glob generated pages (sorted numerically)
            generated_pages = sorted(
                edition_dir.glob(f"temp-{projection}-*.png"),
                key=lambda p: int(p.stem.split("-")[-1])
            )
            
            for index, page_png in enumerate(generated_pages):
                page_number = index + 1
                baseline_name = f"{projection}-page-{page_number:03d}.png"
                baseline_path = self.baseline_dir / baseline_name
                
                if self.update_baselines:
                    # Baseline update mode: copy page to baselines directory
                    shutil.copy(page_png, baseline_path)
                else:
                    # Validation mode: assert baseline exists and compare
                    if not baseline_path.exists():
                        raise AssertionError(
                            f"Visual baseline does not exist for {projection} page {page_number}.\n"
                            f"Run tests with '--update-baselines' to generate baselines."
                        )
                    self._assert_pixel_match(page_png, baseline_path, projection, page_number)
                
                self.steps.append({
                    "projection": projection,
                    "page": page_number,
                    "image_path": f"./baselines/{baseline_name}"
                })

    def _assert_pixel_match(self, candidate_path: Path, baseline_path: Path, projection: str, page: int):
        img_cand = Image.open(candidate_path).convert("RGB")
        img_base = Image.open(baseline_path).convert("RGB")
        
        if img_cand.size != img_base.size:
            raise AssertionError(
                f"Dimension mismatch for visual validation on {projection} page {page}:\n"
                f"Candidate {img_cand.size} vs Baseline {img_base.size}."
            )
            
        diff = ImageChops.difference(img_cand, img_base)
        bbox = diff.getbbox()
        
        if bbox is not None:
            # Highlight differences in pure red
            diff_dir = self.scenario_dir / "diffs"
            diff_dir.mkdir(exist_ok=True)
            diff_path = diff_dir / f"diff-{projection}-page-{page:03d}.png"
            
            import numpy as np
            arr_cand = np.array(img_cand)
            arr_base = np.array(img_base)
            
            mask = np.any(arr_cand != arr_base, axis=-1)
            out_arr = arr_cand.copy()
            out_arr[mask] = [255, 0, 0] # Highlight differing pixels in pure red
            
            Image.fromarray(out_arr).save(diff_path)
            
            raise AssertionError(
                f"Visual layout regression detected on {projection} page {page}!\n"
                f"Candidate image: {candidate_path}\n"
                f"Baseline image: {baseline_path}\n"
                f"Diff highlight saved to: {diff_path}"
            )

    def generate_markdown(self, title: str):
        readme_path = self.scenario_dir / "README.md"
        content = f"# E2E Visual Verification Run: {title}\n\n"
        content += "This walkthrough is auto-generated by the E2E visual test run. Verify the page rendering below:\n\n"
        
        from collections import defaultdict
        by_projection = defaultdict(list)
        for step in self.steps:
            by_projection[step["projection"]].append(step)
            
        for projection, pages in sorted(by_projection.items()):
            content += f"## Projection: `{projection}`\n\n"
            for p in pages:
                content += f"### Page {p['page']}\n\n"
                content += f"![{projection} Page {p['page']}]({p['image_path']})\n\n"
                content += "**Layout Checklist:**\n"
                content += f"- [x] Page structure and spacing for `{projection}` is correct\n"
                content += "- [x] Font selection and typography contains no replacements\n"
                content += "- [x] TikZ and math formulas render properly\n\n"
            content += "---\n\n"
            
        readme_path.write_text(content, encoding="utf-8")
